# Generated by Django 5.1.1 on 2024-12-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
