# Generated by Django 5.1.1 on 2024-12-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_authuser_task_is_favorite_alter_task_complete_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['important', 'complete']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='task',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
