# Generated by Django 5.1.1 on 2024-12-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_categories_category_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
