# Generated by Django 5.1.4 on 2025-01-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
    ]
