# Generated by Django 5.1.1 on 2025-02-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_category_name_profile_delete_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
